'use strict';
const history = document.querySelector('#history');
const detail = document.querySelector('#detail');
const notice = document.querySelector('#notice');
const emptyTemplate = detail.firstElementChild.cloneNode(true);
let selected = null;
let requestSequence = 0;
function node(tag, text, className) {
  const element = document.createElement(tag);
  if (text !== undefined) element.textContent = text;
  if (className) element.className = className;
  return element;
}
function metricLabel(value) { return value.replace(/_/g, ' ').replace(/^./, letter => letter.toUpperCase()); }
function badge(status) { return node('span', status, `badge ${status}`); }
function number(value) { return value == null ? '—' : Number(value).toFixed(3); }
function metricValue(value, metric, delta = false) {
  if (value == null) return '—';
  if (['latency_ms', 'p95_latency_ms'].includes(metric)) return `${value.toFixed(1)} ms`;
  if (metric === 'cost') return `$${value.toFixed(4)}`;
  return `${(value * 100).toFixed(1)}${delta ? ' pp' : '%'}`;
}
function checkDescription(spec, metric) {
  const operational = {
    latency_ms: 'Average answer time. Lower is better.',
    p95_latency_ms: 'Answer time at the 95th percentile. Lower is better.',
    cost: 'Estimated target cost from configured prices and reported usage. Lower is better.',
    error_rate: 'Share of target calls that failed. Lower is better.'
  };
  if (operational[metric]) return operational[metric];
  const descriptions = {
    exact_match: 'Matches the expected answer.', contains: 'Includes the required facts or phrases.',
    excludes: 'Avoids prohibited claims or phrases.', regex: 'Matches a configured text pattern.',
    json_schema: 'Returns the required data structure.', numeric: 'Falls within the allowed numeric range.',
    retrieval_recall: 'Finds the expected supporting documents. Higher is better.',
    retrieval_precision: 'Measures relevant documents within the retrieval limit. Higher is better.',
    citation_validity: 'Checks that cited passages were retrieved. It does not prove a claim is true.',
    faithfulness: 'A model judges whether the source passages support the answer. This is a judgment, not a guarantee.',
    judge: 'A model scores the answer against the configured rubric.'
  };
  return descriptions[spec?.kind] ?? 'Checks the configured quality rule.';
}
function sourceDescription(run) {
  if (run.target_config.evidence_mode === 'simulated') return 'Simulated responses · No real AI calls were made.';
  if (run.target_config.kind === 'mock') return 'Predefined test answers · These were not generated by AI.';
  if (run.target_config.callable === 'evalforge.demos.support:answer_case') return 'Rule-based support demo · These answers use policy rules, not AI.';
  if (run.target_config.kind === 'retrieval') return 'Document retrieval only · Searches real passages. No AI answers or judge calls were made.';
  if (run.target_config.kind === 'rag') return 'RAG application · Retrieves document passages, then asks the configured model to answer using them.';
  if (run.target_config.kind === 'chat') return 'Model application · Answers come from the configured model provider.';
  return 'Local application · Its own code determines whether answers use rules or a model.';
}
function toggleHelp(open) {
  const panel = document.querySelector('#getting-started');
  panel.hidden = !open;
  document.querySelector('#help').setAttribute('aria-expanded', String(open));
  if (open) panel.scrollIntoView({behavior:'smooth', block:'start'});
}
async function get(url) {
  const response = await fetch(url);
  if (!response.ok) throw new Error('Could not read this experiment. Check that its saved files are complete.');
  return response.json();
}
function answerPanel(label, row, run) {
  const box = node('div', undefined, 'answer');
  box.append(node('h3', label), node('p', row.target.output ?? row.target.error ?? 'No answer saved', 'answer-text'));
  if (run.target_config.provider?.model) box.append(node('p', `Configured model: ${run.target_config.provider.model}`, 'muted'));
  box.append(node('p', `${run.target_config.kind ?? 'Unknown'} target · ${row.target.latency_ms.toFixed(1)} ms`, 'muted'));
  if (row.target.error) box.append(node('p', `Execution error: ${row.target.error}`));
  const evaluations = node('div', undefined, 'evaluations');
  for (const evaluation of row.evaluations) {
    const line = node('div', undefined, 'evaluation');
    const spec = run.evaluators.find(e => e.metric === evaluation.metric);
    let explanation = evaluation.explanation;
    if (['contains', 'excludes'].includes(spec?.kind)) {
      if (evaluation.status === 'PASS') explanation = spec.kind === 'contains' ? 'Required text is present.' : 'No prohibited text found.';
      if (evaluation.status === 'FAIL' && explanation.startsWith('failed strings:')) explanation = explanation.replace('failed strings:', spec.kind === 'contains' ? 'Missing required text:' : 'Prohibited text found:');
    }
    line.append(node('strong', `${metricLabel(evaluation.metric)} · ${metricValue(evaluation.score, evaluation.metric)}`), badge(evaluation.status), node('span', explanation, 'explanation'));
    evaluations.append(line);
    if (Array.isArray(evaluation.metadata.evidence) && evaluation.metadata.evidence.length) line.append(node('p', `Judge evidence: ${evaluation.metadata.evidence.join('; ')}`, 'muted judge-evidence'));
  }
  box.append(evaluations);
  const trace = row.target.retrieval;
  if (trace) {
    const evidence = node('details');
    evidence.append(node('summary', `${run.target_config.kind === 'retrieval' ? 'Retrieved sources' : 'Documents used to answer'} · ${trace.passages.length} passages`));
    evidence.append(node('p', 'These are the passages the application retrieved. Search scores measure text relevance, not answer correctness.', 'muted'));
    evidence.append(node('p', `Corpus: ${trace.corpus_hash}`, 'source'));
    if (!trace.passages.length) evidence.append(node('p', 'No matching passages were retrieved.'));
    for (const passage of trace.passages) {
      const block = node('div', undefined, 'passage');
      block.append(node('strong', `${passage.rank}. ${passage.document_id} · ${passage.heading}`), node('p', passage.text), node('p', `${passage.chunk_id} · Search score ${number(passage.score)}`, 'source'));
      evidence.append(block);
    }
    evidence.append(node('p', `Citations: ${trace.citations.join(', ') || 'None'}`, 'source'));
    box.append(evidence);
  }
  return box;
}
function showExperiment(experiment) {
  detail.replaceChildren();
  const {baseline, candidate, comparison} = experiment;
  const overview = node('div', undefined, 'card overview');
  const title = node('div', undefined, 'title-row');
  title.append(node('h2', candidate.dataset_name), badge(comparison.status));
  overview.append(title, node('p', `${baseline.target_name} → ${candidate.target_name}`, 'run-description'), node('p', `${candidate.cases.length} questions · ${new Date(candidate.created_at).toLocaleString()}`, 'muted'));
  const previous = new Map(baseline.cases.map(row => [row.case.id, row]));
  const affectedIds = new Set(comparison.gates.filter(gate => gate.status !== 'PASS').flatMap(gate => gate.case_ids));
  function needsAttention(row) {
    const before = previous.get(row.case.id);
    return affectedIds.has(row.case.id) || row.target.status === 'ERROR' ||
      row.evaluations.some(e => ['FAIL', 'ERROR', 'UNKNOWN'].includes(e.status)) ||
      (before && (before.target.status === 'ERROR' || before.evaluations.some(e => ['ERROR', 'UNKNOWN'].includes(e.status))));
  }
  const affectedCount = candidate.cases.filter(needsAttention).length;
  const affectedTopics = [...new Set(candidate.cases.filter(needsAttention).map(row => row.case.category))];
  const warningCount = comparison.gates.filter(gate => gate.rule.severity === 'warn' && gate.status === 'FAIL').length;
  const unmetCount = comparison.gates.filter(gate => gate.rule.severity === 'block' && gate.status !== 'PASS').length;
  const outcome = node('section', undefined, `outcome ${comparison.status}`);
  const outcomeTitle = comparison.status === 'ERROR' ? 'Evaluation incomplete' : comparison.status === 'FAIL' ? 'Change blocked' : warningCount ? 'Passed with warnings' : 'Passed required checks';
  const outcomeText = comparison.status === 'ERROR' ? 'An execution or evidence problem prevented a reliable decision. Resolve the reported errors, then test again.' : comparison.status === 'FAIL' ? `${unmetCount} required ${unmetCount === 1 ? 'check was' : 'checks were'} not met. Review the differences below before accepting this change.` : warningCount ? `${warningCount} warning ${warningCount === 1 ? 'check needs' : 'checks need'} review. Required checks passed; inspect the warnings before accepting the change.` : 'The candidate met all configured required checks. This does not guarantee correctness beyond this test set.';
  outcome.append(node('h2', outcomeTitle), node('p', outcomeText));
  if (affectedTopics.length) outcome.append(node('p', `Topics needing attention: ${affectedTopics.join(', ')}.`, 'affected-topics'));
  const actions = node('div', undefined, 'outcome-actions');
  const review = node('button', affectedCount ? `Review ${affectedCount} affected ${affectedCount === 1 ? 'question' : 'questions'}` : 'Review all questions');
  const rerun = node('button', 'How to test again', 'secondary');
  rerun.addEventListener('click', () => toggleHelp(true));
  actions.append(review, rerun); outcome.append(actions);
  overview.append(outcome);

  overview.append(node('p', 'Scores compare the reference version (baseline) with your changed version (candidate).', 'score-guide'));
  const gates = node('div', undefined, 'gates');
  for (const gate of comparison.gates) {
    const card = node('div', undefined, 'gate');
    const heading = node('div', undefined, 'gate-title');
    heading.append(node('strong', `${metricLabel(gate.rule.metric)}${gate.rule.category ? ` · ${gate.rule.category}` : ''}`), badge(gate.status));
    const spec = candidate.evaluators.find(e => e.metric === gate.rule.metric);
    card.append(node('p', checkDescription(spec, gate.rule.metric), 'metric-help'));
    const values = node('div', undefined, 'gate-values');
    const before = node('span', metricValue(gate.baseline, gate.rule.metric), 'before');
    before.setAttribute('aria-label', `Baseline: ${metricValue(gate.baseline, gate.rule.metric)}`);
    const after = node('strong', metricValue(gate.candidate, gate.rule.metric));
    after.setAttribute('aria-label', `Candidate: ${metricValue(gate.candidate, gate.rule.metric)}`);
    values.append(before, node('span', '→', 'arrow'), after);
    const explanation = node('details');
    explanation.append(node('summary', 'Decision details'), node('p', `${gate.rule.severity === 'warn' ? 'Warning check' : 'Required check'} · ${gate.explanation}`));
    const deltaText = gate.delta == null ? 'No reliable comparison available' : ['latency_ms', 'p95_latency_ms', 'cost'].includes(gate.rule.metric) ? `${metricValue(gate.delta, gate.rule.metric, true)} change from baseline` : `${Math.abs(gate.delta * 100).toFixed(1)} percentage points ${gate.delta < 0 ? 'lower' : gate.delta > 0 ? 'higher' : 'change'}`;
    card.prepend(heading);
    card.append(values, node('p', deltaText, 'delta'), explanation);
    gates.append(card);
  }
  overview.append(gates);
  overview.append(node('p', sourceDescription(candidate), 'provenance'));
  detail.append(overview);
  appendApprovalForm(overview, experiment);
  const filters = node('div', undefined, 'filters');
  const filter = node('select'); filter.setAttribute('aria-label', 'Filter questions');
  for (const [value, label] of [['failed', 'Questions needing attention'], ['all', 'All questions']]) {
    const option = node('option', label); option.value = value; filter.append(option);
  }
  const topic = node('select'); topic.setAttribute('aria-label','Filter by topic');
  const allTopics = node('option','All topics'); allTopics.value=''; topic.append(allTopics);
  for (const category of [...new Set(candidate.cases.map(row=>row.case.category))].sort()) {const option=node('option',category.replaceAll('_',' '));option.value=category;topic.append(option);}
  const search = node('input');search.type='search';search.placeholder='Find a question';search.setAttribute('aria-label','Search questions');
  filters.append(node('h2', 'Question details'), filter, topic, search); detail.append(filters);
  const cases = node('div'); detail.append(cases);
  review.addEventListener('click', () => {
    filter.value = affectedCount ? 'failed' : 'all';
    renderCases();
    filters.scrollIntoView({behavior:'smooth', block:'start'});
    filter.focus({preventScroll:true});
  });
  function renderCases() {
    cases.replaceChildren();
    for (const row of candidate.cases) {
      const before = previous.get(row.case.id);
      if (filter.value === 'failed' && !needsAttention(row)) continue;
      if (topic.value && row.case.category !== topic.value) continue;
      const questionText = typeof row.case.input === 'string' ? row.case.input : JSON.stringify(row.case.input);
      if (search.value.trim() && !`${row.case.id} ${questionText}`.toLowerCase().includes(search.value.trim().toLowerCase())) continue;
      const card = node('article', undefined, 'card');
      const head = node('div', undefined, 'case-head');
      const meta = node('div', undefined, 'case-meta');
      meta.append(node('span', row.case.category), node('span', '·'), node('span', row.case.id));
      if (row.case.critical) meta.append(node('span', 'Must-pass question', 'critical'));
      head.append(meta, node('p', typeof row.case.input === 'string' ? row.case.input : JSON.stringify(row.case.input), 'case-question'));
      if (row.case.reference_answer != null) {
        const reference = node('details', undefined, 'reference');
        reference.append(node('summary', 'Expected answer'), node('p', `${row.case.reference_answer} (evaluation only)`));
        head.append(reference);
      }
      card.append(head);
      const panels = node('div', undefined, 'answers');
      if (before) panels.append(answerPanel('ORIGINAL VERSION · BASELINE', before, baseline));
      panels.append(answerPanel('CHANGED VERSION · CANDIDATE', row, candidate)); card.append(panels); cases.append(card);
    }
    if (!cases.childElementCount) cases.append(node('p', 'No individual questions need attention in this view. Check the score decisions above, or choose All questions to inspect every answer.'));
  }
  filter.addEventListener('change', renderCases);
  topic.addEventListener('change', renderCases); search.addEventListener('input',renderCases); renderCases();
}
async function selectExperiment(id) {
  selected = id;
  const sequence = ++requestSequence;
  for (const button of history.querySelectorAll('button')) {
    const active = button.dataset.id === id;
    button.classList.toggle('selected', active);
    button.setAttribute('aria-pressed', String(active));
  }
  try {
    const experiment = await get(`/api/experiments/${encodeURIComponent(id)}`);
    if (sequence !== requestSequence) return;
    showExperiment(experiment);
  } catch (error) { if (sequence === requestSequence) notice.textContent = error.message; }
}
async function refresh() {
  try {
    const response = await get('/api/experiments');
    notice.textContent = response.invalid_artifacts ? `${response.invalid_artifacts} incomplete or invalid artifact folders were skipped.` : '';
    history.replaceChildren();
    for (const run of response.experiments) {
      const button = node('button', undefined, 'run'); button.dataset.id = run.directory;
      const top = node('div', undefined, 'run-top');
      top.append(node('strong', run.dataset), badge(run.status));
      button.append(top, node('span', `${run.baseline} → ${run.candidate}`, 'muted'), node('span', new Date(run.created_at).toLocaleString(), 'muted'));
      button.addEventListener('click', () => selectExperiment(run.directory)); history.append(button);
    }
    if (response.experiments.length) {
      const id = response.experiments.some(run => run.directory === selected) ? selected : response.experiments[0].directory;
      await selectExperiment(id);
    } else { selected = null; requestSequence++; detail.replaceChildren(emptyTemplate.cloneNode(true)); history.append(node('p', 'No saved tests yet. Start with the demonstration on the right.', 'muted')); }
  } catch (error) { notice.textContent = error.message; }
}
document.querySelector('#help').addEventListener('click', () => toggleHelp(document.querySelector('#getting-started').hidden));
document.querySelector('#refresh').addEventListener('click', refresh);
refresh();

let previewRequest = 0;
let setup = {profiles:[]};
let approvedBaselines = [];
let jobLimit = 10;
let activeJob = null;
let pollTimer = null;
const runProfile = document.querySelector('#run-profile');
const startRun = document.querySelector('#start-run');
const consent = document.querySelector('#confirm-model');
const jobStatus = document.querySelector('#job-status');
function renderProfile() {
  const profile = setup.profiles.find(profile => profile.id === runProfile.value);
  const issues = document.querySelector('#setup-issues');
  issues.replaceChildren();
  for (const issue of profile?.issues ?? []) issues.append(node('li', issue));
  document.querySelector('#paid-consent').hidden = !profile?.uses_model;
  document.querySelector('#source-preview').hidden = !profile?.can_preview_retrieval;
  document.querySelector('#model-setup').hidden = !profile?.model_settings;
  const retrievalOnly = profile?.can_preview_retrieval && !profile.uses_model;
  document.querySelector('.next-step').textContent = retrievalOnly ? '2. Evaluate retrieval: Run evaluation checks whether each question finds its labeled supporting document. No AI key is needed.' : '2. Evaluate AI answers: Complete the model setup below, then Run evaluation to generate and check model answers.';
  startRun.textContent = retrievalOnly ? 'Run retrieval evaluation · no AI key' : 'Run evaluation';
  document.querySelector('#cancel-run').hidden = !activeJob;
  renderBaselineOptions(profile);
  document.querySelector('#save-model').disabled = !!activeJob;
  for (const button of document.querySelectorAll('.approval-submit')) button.disabled = !setup.baselines_enabled;
  startRun.disabled = !!activeJob || !profile?.ready || (profile.uses_model && !consent.checked);
  document.querySelector('#profile-description').textContent = profile ? `${profile.questions ?? 'Unknown'} questions · ${profile.baseline ?? 'Baseline'} → ${profile.candidate ?? 'Candidate'} · ${profile.uses_model ? `AI evaluation · up to ${profile.request_limit ?? 'unspecified'} model requests, including retries.` : profile.can_preview_retrieval ? 'Real document retrieval · no AI calls or answer generation.' : 'Local application or predefined fixtures. Its configuration determines behavior.'}` : 'No tests enabled for browser execution. Start the dashboard with --config examples/support/offline.json for the rule-based demo, or --config examples/rag/live.json for a configured model test.';
}
async function loadSetup() {
  try {
    const previous = runProfile.value;
    setup = await get('/api/setup');
    clearPreview();
    runProfile.replaceChildren();
    for (const profile of setup.profiles) {
      const option = node('option', profile.name); option.value = profile.id; runProfile.append(option);
    }
    if (!setup.profiles.length) runProfile.append(node('option', 'No configurations enabled'));
    if (setup.profiles.some(profile => profile.id === previous)) runProfile.value = previous;
    runProfile.disabled = !setup.profiles.length || !!activeJob;
    fillModelSettings();
    await loadBaselines();
    renderProfile();
    if (setup.active_job && !activeJob) { activeJob = setup.active_job; renderProfile(); pollJob(); }
  } catch (error) { jobStatus.textContent = error.message; startRun.disabled = true; }
}
async function pollJob() {
  if (!activeJob) return;
  try {
    const job = await get(`/api/jobs/${encodeURIComponent(activeJob)}`);
    jobStatus.replaceChildren(node('span', `${job.status === 'RUNNING' ? 'Running' : job.status === 'QUEUED' ? 'Queued' : job.status === 'CANCELLING' ? 'Stopping' : job.status === 'CANCELLED' ? 'Stopped' : job.status === 'COMPLETED' ? 'Finished' : job.status === 'INTERRUPTED' ? 'Interrupted' : 'Could not complete'} · ${job.message}`));
    if (['QUEUED', 'RUNNING', 'CANCELLING'].includes(job.status)) {
      pollTimer = setTimeout(pollJob, 1000);
      return;
    }
    activeJob = null; runProfile.disabled = !setup.profiles.length; renderProfile();
    await refresh();
    await loadJobs();
    await loadBaselines();
    if (job.experiment_directory) {
      await selectExperiment(job.experiment_directory);
      const open = node('button', 'View results');
      open.addEventListener('click', () => { detail.scrollIntoView({behavior:'smooth'}); });
      jobStatus.append(open);
    }
  } catch (error) {
    activeJob = null; runProfile.disabled = !setup.profiles.length; renderProfile();
    jobStatus.textContent = `${error.message} Refresh setup to check whether a job is still running.`;
  }
}
startRun.addEventListener('click', async () => {
  const profile = setup.profiles.find(profile => profile.id === runProfile.value);
  if (!profile?.ready || activeJob || (profile.uses_model && !consent.checked)) return;
  startRun.disabled = true;
  try {
    const response = await fetch('/api/jobs', {method:'POST', headers:{'Content-Type':'application/json', 'X-EvalForge-Token':setup.session_token}, body:JSON.stringify({profile_id:profile.id, confirm_model_calls:consent.checked, baseline_name:document.querySelector('#baseline-selection').value || null})});
    const job = await response.json();
    if (!response.ok) throw new Error(job.error ?? 'Could not start the evaluation.');
    activeJob = job.id; runProfile.disabled = true; renderProfile();
    clearTimeout(pollTimer); pollJob();
  } catch (error) { jobStatus.textContent = error.message; await loadSetup(); }
});
runProfile.addEventListener('change', () => { consent.checked = false; clearPreview(); fillModelSettings(); renderProfile(); });
consent.addEventListener('change', renderProfile);
document.querySelector('#check-setup').addEventListener('click', loadSetup);
loadSetup();

function clearPreview() {
  previewRequest += 1;
  document.querySelector('#preview-results').replaceChildren();
  document.querySelector('#preview-status').textContent = '';
  document.querySelector('#preview-sources').disabled = false;
}
document.querySelector('#preview-form').addEventListener('submit', async event => {
  event.preventDefault();
  const profileId = runProfile.value;
  const question = document.querySelector('#preview-question').value.trim();
  const status = document.querySelector('#preview-status');
  const results = document.querySelector('#preview-results');
  if (!question) { status.textContent = 'Enter a question first.'; return; }
  const request = ++previewRequest;
  document.querySelector('#preview-sources').disabled = true;
  results.replaceChildren(); status.textContent = 'Searching both document collections…';
  try {
    const response = await fetch('/api/retrieval', {method:'POST', headers:{'Content-Type':'application/json','X-EvalForge-Token':setup.session_token}, body:JSON.stringify({profile_id:profileId,question})});
    const preview = await response.json();
    if (request !== previewRequest) return;
    if (!response.ok) throw new Error(preview.error ?? 'Could not preview sources.');
    status.textContent = `Search complete for “${preview.question}”. No AI answer was generated and no evaluation was saved.`;
    for (const [key, label] of [['baseline','Original version · baseline'],['candidate','Changed version · candidate']]) {
      const target = preview[key];
      const column = node('section', undefined, 'preview-column');
      column.append(node('h4', label), node('p', `${target.name} · ${target.documents} documents · ${target.trace.passages.length} matching passage${target.trace.passages.length === 1 ? '' : 's'}`));
      if (!target.trace.passages.length) column.append(node('p', 'No matching passages. Check whether the collection contains this topic, or try different wording.', 'empty-sources'));
      for (const passage of target.trace.passages) {
        const card = node('article', undefined, 'preview-passage');
        card.append(node('h5', `${passage.rank}. ${passage.heading}`), node('p', passage.document_id, 'muted'), node('p', passage.text));
        const evidence = node('details');
        evidence.append(node('summary', 'Search details'), node('p', `Word-match score: ${passage.score.toFixed(3)}. This is a ranking score, not AI confidence; scores from different collections are not directly comparable.`), node('code', passage.chunk_id));
        card.append(evidence); column.append(card);
      }
      results.append(column);
    }
  } catch (error) { if (request === previewRequest) status.textContent = `${error.message} Refresh setup and check the registered documents.`; }
  finally { if (request === previewRequest) document.querySelector('#preview-sources').disabled = false; }
});

document.querySelector('#preview-question').addEventListener('input', clearPreview);

async function post(url, payload) {
  const response = await fetch(url, {method:'POST', headers:{'Content-Type':'application/json','X-EvalForge-Token':setup.session_token}, body:JSON.stringify(payload)});
  const data = await response.json();
  if (!response.ok) throw new Error(data.error ?? 'This action could not complete.');
  return data;
}
function stableValue(value) {
  if (Array.isArray(value)) return value.map(stableValue);
  if (value && typeof value === 'object') return Object.fromEntries(Object.keys(value).sort().map(key=>[key,stableValue(value[key])]));
  return value;
}
function evaluatorFingerprint(evaluators) { return evaluators.map(e=>JSON.stringify(stableValue(e))).sort().join('\n'); }
function compatibleBaseline(profile, baseline) {
  return profile && baseline.dataset === profile.dataset && baseline.dataset_version === profile.dataset_version && baseline.dataset_hash === profile.dataset_hash && evaluatorFingerprint(baseline.evaluators) === evaluatorFingerprint(profile.evaluators);
}
function renderBaselineOptions(profile) {
  const select = document.querySelector('#baseline-selection');
  const previous = select.value;
  select.replaceChildren();
  const option = node('option', 'Run the configured original version'); option.value = ''; select.append(option);
  for (const baseline of approvedBaselines.filter(b => compatibleBaseline(profile,b))) {
    const item = node('option', `${baseline.name} · ${baseline.target}`); item.value = baseline.name; select.append(item);
  }
  if ([...select.options].some(option => option.value === previous)) select.value = previous;
  select.disabled = !!activeJob;
}
async function loadBaselines() {
  try {
    approvedBaselines = (await get('/api/baselines')).baselines;
    const panel = document.querySelector('#baseline-history'); panel.replaceChildren();
    for (const baseline of approvedBaselines) {
      const entry = node('details'); entry.append(node('summary', `${baseline.name} · ${baseline.dataset} · ${baseline.target}`));
      for (const approval of baseline.history) entry.append(node('p', `${new Date(approval.approved_at).toLocaleString()} · ${approval.approved_by} · ${approval.run_id} · ${approval.note || 'No note'}`));
      panel.append(entry);
    }
    if (!approvedBaselines.length) panel.append(node('p','No reference versions approved yet. Review a result and use Save a reference version.'));
    renderBaselineOptions(setup.profiles.find(profile => profile.id === runProfile.value));
  } catch (error) { document.querySelector('#baseline-history').textContent = error.message; }
}
function fillModelSettings() {
  const profile = setup.profiles.find(profile => profile.id === runProfile.value);
  const provider = profile?.model_settings;
  document.querySelector('#model-name').value = provider?.model?.startsWith('YOUR_') ? '' : provider?.model ?? '';
  document.querySelector('#judge-name').value = profile?.judge_model?.startsWith('YOUR_') ? '' : profile?.judge_model ?? '';
  document.querySelector('#provider-url').value = provider?.base_url ?? '';
  document.querySelector('#credential-variable').value = provider?.api_key_env ?? '';
  document.querySelector('#model-status').textContent = '';
}
document.querySelector('#model-settings').addEventListener('submit', async event => {
  event.preventDefault();
  const status = document.querySelector('#model-status');
  try {
    await post('/api/configure',{profile_id:runProfile.value, settings:{model:document.querySelector('#model-name').value.trim(),judge_model:document.querySelector('#judge-name').value.trim(),base_url:document.querySelector('#provider-url').value.trim(),api_key_env:document.querySelector('#credential-variable').value.trim()}});
    consent.checked = false; await loadSetup(); status.textContent = 'Settings saved. No model was called. Add the credential locally, restart the dashboard, then check setup before running AI evaluation.';
  } catch (error) { status.textContent = error.message; }
});
async function cancelJob(id) {
  try { await post('/api/cancel',{job_id:id}); activeJob = id; clearTimeout(pollTimer); renderProfile(); await pollJob(); }
  catch (error) { jobStatus.textContent = error.message; await loadJobs(); }
}
document.querySelector('#cancel-run').addEventListener('click', () => { if (activeJob) cancelJob(activeJob); });
async function loadJobs() {
  try {
    const data = await get('/api/jobs');
    const panel = document.querySelector('#job-history'); panel.replaceChildren();
    for (const job of data.jobs.slice(0,jobLimit)) {
      const item = node('article', undefined, 'job-entry');
      const label = {COMPLETED:'Finished',ERROR:'Could not complete',CANCELLED:'Stopped',CANCELLING:'Stopping',RUNNING:'Running',QUEUED:'Queued',INTERRUPTED:'Interrupted'}[job.status];
      item.append(node('strong', `${job.profile ?? 'Saved job'} · ${label}`),node('p', `${new Date(job.created_at).toLocaleString()} · ${job.message}`));
      if (job.comparison_status && job.status === 'COMPLETED') item.append(badge(job.comparison_status));
      if (job.baseline_name) item.append(node('p', `Approved reference: ${job.baseline_name}`));
      if (job.experiment_directory) { const open=node('button','View comparison'); open.addEventListener('click',async () => {await selectExperiment(job.experiment_directory); detail.scrollIntoView({behavior:'smooth'});}); item.append(open); }
      if (['QUEUED','RUNNING'].includes(job.status)) {const stop=node('button','Stop job');stop.addEventListener('click',()=>cancelJob(job.id));item.append(stop);}
      panel.append(item);
    }
    if (!data.jobs.length) panel.append(node('p','No browser jobs yet. Start an evaluation above.'));
    if (data.invalid_jobs) panel.append(node('p',`${data.invalid_jobs} unreadable job records were skipped.`));
    document.querySelector('#more-jobs').hidden = data.jobs.length <= jobLimit;
  } catch (error) {document.querySelector('#job-history').textContent = error.message;}
}
document.querySelector('#refresh-jobs').addEventListener('click',loadJobs);
document.querySelector('#more-jobs').addEventListener('click',()=>{jobLimit+=10;loadJobs();});
function appendApprovalForm(container, experiment) {
  const panel=node('details',undefined,'approval-panel');panel.append(node('summary','Save a reference version'));
  panel.append(node('p','After reviewing this evidence, approve one version for future comparisons. Approval is your decision, not an AI verdict. Execution errors and failed must-pass cases cannot be approved. Your name is an audit label, not a login.'));
  const form=node('form',undefined,'settings-form');
  const side=node('select');side.setAttribute('aria-label','Version to approve');
  for (const [value,label] of [['baseline','Original version'],['candidate','Changed version']]) {const option=node('option',label);option.value=value;side.append(option);}
  const name=node('input');name.required=true;name.maxLength=100;name.setAttribute('aria-label','Reference name');name.placeholder='Reference name';
  const reviewer=node('input');reviewer.required=true;reviewer.maxLength=100;reviewer.setAttribute('aria-label','Reviewer name');reviewer.placeholder='Your name';
  const note=node('input');note.maxLength=1000;note.setAttribute('aria-label','Approval note');note.placeholder='What did you review?';
  const confirm=node('input');confirm.type='checkbox';confirm.required=true;
  const confirmation=node('label');confirmation.append(confirm,node('span',' I reviewed this version and want to use it as a reference.'));
  const submit=node('button','Approve reference','approval-submit');submit.type='submit';submit.disabled=!setup.baselines_enabled;
  form.append(side,name,reviewer,note,confirmation,submit);
  const status=node('p');status.setAttribute('role','status');
  form.addEventListener('submit',async event=>{event.preventDefault();submit.disabled=true;try {await post('/api/approve',{experiment_id:selected,side:side.value,name:name.value.trim(),approved_by:reviewer.value.trim(),note:note.value.trim()});status.textContent='Reference approved and saved locally. Matching tests can now reuse it.';await loadBaselines();}catch(error){status.textContent=error.message;}finally{submit.disabled=false;}});
  panel.append(form,status);container.append(panel);
}
loadJobs();
