'use strict';
const history = document.querySelector('#history');
const detail = document.querySelector('#detail');
const notice = document.querySelector('#notice');
let selected = null;
let requestSequence = 0;
function node(tag, text, className) {
  const element = document.createElement(tag);
  if (text !== undefined) element.textContent = text;
  if (className) element.className = className;
  return element;
}
function badge(status) { return node('span', status, `badge ${status}`); }
function number(value) { return value == null ? '—' : Number(value).toFixed(3); }
function metricValue(value, metric, delta = false) {
  if (value == null) return '—';
  if (['latency_ms', 'p95_latency_ms'].includes(metric)) return `${value.toFixed(1)} ms`;
  if (metric === 'cost') return `$${value.toFixed(4)}`;
  return `${(value * 100).toFixed(1)}${delta ? ' pp' : '%'}`;
}
async function get(url) {
  const response = await fetch(url);
  if (!response.ok) throw new Error('Could not read this experiment. Check that its saved files are complete.');
  return response.json();
}
function answerPanel(label, row, run) {
  const box = node('div', undefined, 'answer');
  box.append(node('h3', label), node('p', row.target.output ?? row.target.error ?? 'No answer saved'));
  if (run.target_config.provider?.model) box.append(node('p', `Configured model: ${run.target_config.provider.model}`, 'muted'));
  box.append(node('p', `${run.target_config.kind ?? 'Unknown'} target · ${row.target.latency_ms.toFixed(1)} ms`, 'muted'));
  if (row.target.error) box.append(node('p', `Execution error: ${row.target.error}`));
  for (const evaluation of row.evaluations) {
    const line = node('div', undefined, 'evaluation');
    line.append(badge(evaluation.status), node('strong', `${evaluation.metric} · ${metricValue(evaluation.score, evaluation.metric)} `), node('span', evaluation.explanation));
    box.append(line);
    if (Array.isArray(evaluation.metadata.evidence) && evaluation.metadata.evidence.length) box.append(node('p', `Judge evidence: ${evaluation.metadata.evidence.join('; ')}`, 'muted'));
  }
  const trace = row.target.retrieval;
  if (trace) {
    const evidence = node('details');
    evidence.append(node('summary', `Retrieved evidence · ${trace.passages.length} passages`));
    evidence.append(node('p', `Corpus: ${trace.corpus_hash}`, 'source'));
    if (!trace.passages.length) evidence.append(node('p', 'No matching passages were retrieved.'));
    for (const passage of trace.passages) {
      const block = node('div', undefined, 'passage');
      block.append(node('strong', `${passage.rank}. ${passage.document_id} · ${passage.heading}`), node('p', passage.text), node('p', `${passage.chunk_id} · Search score ${number(passage.score)}`, 'source'));
      evidence.append(block);
    }
    evidence.append(node('p', `Citations: ${trace.citations.join(', ') || 'None'}`, 'source'));
    box.append(evidence);
  }
  return box;
}
function showExperiment(experiment) {
  detail.replaceChildren();
  const {baseline, candidate, comparison} = experiment;
  const overview = node('div', undefined, 'card');
  const title = node('div', undefined, 'title-row');
  title.append(badge(comparison.status), node('h2', candidate.dataset_name));
  overview.append(title, node('p', `${baseline.target_name} → ${candidate.target_name}`), node('p', `${candidate.cases.length} questions · ${new Date(candidate.created_at).toLocaleString()}`, 'muted'));
  const kind = candidate.target_config.kind;
  overview.append(node('p', candidate.target_config.evidence_mode === 'simulated' ? 'Simulated provider responses for UI verification. No real AI calls were made.' : kind === 'rag' ? 'RAG target: answers use the configured model. Tests may also produce saved runs with simulated provider responses; inspect how the run was created.' : kind === 'mock' ? 'Fixture responses: these answers were predefined, not generated by AI.' : kind === 'local' ? 'Local application: inspect its configuration to establish whether it uses a model or rules.' : 'Model target: answers use the configured provider.', 'muted'));
  const table = node('table');
  const head = node('tr');
  for (const label of ['Check', 'Baseline', 'Candidate', 'Change', 'Decision']) head.append(node('th', label));
  table.append(head);
  for (const gate of comparison.gates) {
    const row = node('tr');
    row.append(node('td', `${gate.rule.metric}${gate.rule.category ? ` · ${gate.rule.category}` : ''}`), node('td', metricValue(gate.baseline, gate.rule.metric)), node('td', metricValue(gate.candidate, gate.rule.metric)), node('td', metricValue(gate.delta, gate.rule.metric, true)));
    const decision = node('td', undefined, 'reason');
    decision.append(badge(gate.status), node('p', `${gate.rule.severity === 'warn' ? 'Warning check' : 'Required check'} · ${gate.explanation}`));
    row.append(decision); table.append(row);
  }
  const wrap = node('div', undefined, 'table-wrap'); wrap.append(table); overview.append(wrap); detail.append(overview);
  const filters = node('div', undefined, 'filters');
  const filter = node('select'); filter.setAttribute('aria-label', 'Filter questions');
  for (const [value, label] of [['failed', 'Failures and errors'], ['all', 'All questions']]) {
    const option = node('option', label); option.value = value; filter.append(option);
  }
  filters.append(node('h2', 'Question details'), filter); detail.append(filters);
  const cases = node('div'); detail.append(cases);
  const previous = new Map(baseline.cases.map(row => [row.case.id, row]));
  function renderCases() {
    cases.replaceChildren();
    for (const row of candidate.cases) {
      const failed = row.target.status === 'ERROR' || row.evaluations.some(e => ['FAIL', 'ERROR', 'UNKNOWN'].includes(e.status));
      const before = previous.get(row.case.id);
      const baselineFailed = before && (before.target.status === 'ERROR' || before.evaluations.some(e => ['ERROR', 'UNKNOWN'].includes(e.status)));
      if (filter.value === 'failed' && !failed && !baselineFailed) continue;
      const card = node('article', undefined, 'card');
      card.append(node('p', `${row.case.id} · ${row.case.category}${row.case.critical ? ' · Critical question' : ''}`, 'muted'), node('p', typeof row.case.input === 'string' ? row.case.input : JSON.stringify(row.case.input), 'case-question'));
      if (row.case.reference_answer != null) card.append(node('p', `Expected answer (evaluation only): ${row.case.reference_answer}`, 'muted'));
      const panels = node('div', undefined, 'answers');
      if (before) panels.append(answerPanel('BASELINE', before, baseline));
      panels.append(answerPanel('CANDIDATE', row, candidate)); card.append(panels); cases.append(card);
    }
    if (!cases.childElementCount) cases.append(node('p', 'No question-level failures in this view. Aggregate gates may still fail; inspect their explanations above.'));
  }
  filter.addEventListener('change', renderCases); renderCases();
}
async function selectExperiment(id) {
  selected = id;
  const sequence = ++requestSequence;
  for (const button of history.querySelectorAll('button')) button.classList.toggle('selected', button.dataset.id === id);
  try {
    const experiment = await get(`/api/experiments/${encodeURIComponent(id)}`);
    if (sequence !== requestSequence) return;
    showExperiment(experiment);
  } catch (error) { if (sequence === requestSequence) notice.textContent = error.message; }
}
async function refresh() {
  try {
    const response = await get('/api/experiments');
    notice.textContent = response.invalid_artifacts ? `${response.invalid_artifacts} incomplete or invalid artifact folders were skipped.` : '';
    history.replaceChildren();
    for (const run of response.experiments) {
      const button = node('button', undefined, 'run'); button.dataset.id = run.directory;
      button.append(badge(run.status), node('strong', run.dataset), node('span', `${run.baseline} → ${run.candidate}`, 'muted'), node('span', new Date(run.created_at).toLocaleString(), 'muted'));
      button.addEventListener('click', () => selectExperiment(run.directory)); history.append(button);
    }
    if (response.experiments.length) {
      const id = response.experiments.some(run => run.directory === selected) ? selected : response.experiments[0].directory;
      await selectExperiment(id);
    } else { history.append(node('p', 'No saved experiments yet.', 'muted')); }
  } catch (error) { notice.textContent = error.message; }
}
document.querySelector('#refresh').addEventListener('click', refresh);
refresh();
