'use strict';
const history = document.querySelector('#history');
const detail = document.querySelector('#detail');
const notice = document.querySelector('#notice');
const emptyTemplate = detail.firstElementChild.cloneNode(true);
let selected = null;
let requestSequence = 0;
function node(tag, text, className) {
  const element = document.createElement(tag);
  if (text !== undefined) element.textContent = text;
  if (className) element.className = className;
  return element;
}
function metricLabel(value) { return value.replace(/_/g, ' ').replace(/^./, letter => letter.toUpperCase()); }
function badge(status) { return node('span', status, `badge ${status}`); }
function number(value) { return value == null ? '—' : Number(value).toFixed(3); }
function metricValue(value, metric, delta = false) {
  if (value == null) return '—';
  if (['latency_ms', 'p95_latency_ms'].includes(metric)) return `${value.toFixed(1)} ms`;
  if (metric === 'cost') return `$${value.toFixed(4)}`;
  return `${(value * 100).toFixed(1)}${delta ? ' pp' : '%'}`;
}
function checkDescription(spec, metric) {
  const operational = {
    latency_ms: 'Average answer time. Lower is better.',
    p95_latency_ms: 'Answer time at the 95th percentile. Lower is better.',
    cost: 'Estimated target cost from configured prices and reported usage. Lower is better.',
    error_rate: 'Share of target calls that failed. Lower is better.'
  };
  if (operational[metric]) return operational[metric];
  const descriptions = {
    exact_match: 'Matches the expected answer.', contains: 'Includes the required facts or phrases.',
    excludes: 'Avoids prohibited claims or phrases.', regex: 'Matches a configured text pattern.',
    json_schema: 'Returns the required data structure.', numeric: 'Falls within the allowed numeric range.',
    retrieval_recall: 'Finds the expected supporting documents. Higher is better.',
    retrieval_precision: 'Measures relevant documents within the retrieval limit. Higher is better.',
    citation_validity: 'Checks that cited passages were retrieved. It does not prove a claim is true.',
    faithfulness: 'A model judges whether the source passages support the answer. This is a judgment, not a guarantee.',
    judge: 'A model scores the answer against the configured rubric.'
  };
  return descriptions[spec?.kind] ?? 'Checks the configured quality rule.';
}
function sourceDescription(run) {
  if (run.target_config.evidence_mode === 'simulated') return 'Simulated responses · No real AI calls were made.';
  if (run.target_config.kind === 'mock') return 'Predefined test answers · These were not generated by AI.';
  if (run.target_config.callable === 'evalforge.demos.support:answer_case') return 'Rule-based support demo · These answers use policy rules, not AI.';
  if (run.target_config.kind === 'rag') return 'RAG application · Retrieves document passages, then asks the configured model to answer using them.';
  if (run.target_config.kind === 'chat') return 'Model application · Answers come from the configured model provider.';
  return 'Local application · Its own code determines whether answers use rules or a model.';
}
function toggleHelp(open) {
  const panel = document.querySelector('#getting-started');
  panel.hidden = !open;
  document.querySelector('#help').setAttribute('aria-expanded', String(open));
  if (open) panel.scrollIntoView({behavior:'smooth', block:'start'});
}
async function get(url) {
  const response = await fetch(url);
  if (!response.ok) throw new Error('Could not read this experiment. Check that its saved files are complete.');
  return response.json();
}
function answerPanel(label, row, run) {
  const box = node('div', undefined, 'answer');
  box.append(node('h3', label), node('p', row.target.output ?? row.target.error ?? 'No answer saved', 'answer-text'));
  if (run.target_config.provider?.model) box.append(node('p', `Configured model: ${run.target_config.provider.model}`, 'muted'));
  box.append(node('p', `${run.target_config.kind ?? 'Unknown'} target · ${row.target.latency_ms.toFixed(1)} ms`, 'muted'));
  if (row.target.error) box.append(node('p', `Execution error: ${row.target.error}`));
  const evaluations = node('div', undefined, 'evaluations');
  for (const evaluation of row.evaluations) {
    const line = node('div', undefined, 'evaluation');
    const spec = run.evaluators.find(e => e.metric === evaluation.metric);
    let explanation = evaluation.explanation;
    if (['contains', 'excludes'].includes(spec?.kind)) {
      if (evaluation.status === 'PASS') explanation = spec.kind === 'contains' ? 'Required text is present.' : 'No prohibited text found.';
      if (evaluation.status === 'FAIL' && explanation.startsWith('failed strings:')) explanation = explanation.replace('failed strings:', spec.kind === 'contains' ? 'Missing required text:' : 'Prohibited text found:');
    }
    line.append(node('strong', `${metricLabel(evaluation.metric)} · ${metricValue(evaluation.score, evaluation.metric)}`), badge(evaluation.status), node('span', explanation, 'explanation'));
    evaluations.append(line);
    if (Array.isArray(evaluation.metadata.evidence) && evaluation.metadata.evidence.length) line.append(node('p', `Judge evidence: ${evaluation.metadata.evidence.join('; ')}`, 'muted judge-evidence'));
  }
  box.append(evaluations);
  const trace = row.target.retrieval;
  if (trace) {
    const evidence = node('details');
    evidence.append(node('summary', `Documents used to answer · ${trace.passages.length} passages`));
    evidence.append(node('p', 'These are the passages the application retrieved. Search scores measure text relevance, not answer correctness.', 'muted'));
    evidence.append(node('p', `Corpus: ${trace.corpus_hash}`, 'source'));
    if (!trace.passages.length) evidence.append(node('p', 'No matching passages were retrieved.'));
    for (const passage of trace.passages) {
      const block = node('div', undefined, 'passage');
      block.append(node('strong', `${passage.rank}. ${passage.document_id} · ${passage.heading}`), node('p', passage.text), node('p', `${passage.chunk_id} · Search score ${number(passage.score)}`, 'source'));
      evidence.append(block);
    }
    evidence.append(node('p', `Citations: ${trace.citations.join(', ') || 'None'}`, 'source'));
    box.append(evidence);
  }
  return box;
}
function showExperiment(experiment) {
  detail.replaceChildren();
  const {baseline, candidate, comparison} = experiment;
  const overview = node('div', undefined, 'card overview');
  const title = node('div', undefined, 'title-row');
  title.append(node('h2', candidate.dataset_name), badge(comparison.status));
  overview.append(title, node('p', `${baseline.target_name} → ${candidate.target_name}`, 'run-description'), node('p', `${candidate.cases.length} questions · ${new Date(candidate.created_at).toLocaleString()}`, 'muted'));
  const previous = new Map(baseline.cases.map(row => [row.case.id, row]));
  const affectedIds = new Set(comparison.gates.filter(gate => gate.status !== 'PASS').flatMap(gate => gate.case_ids));
  function needsAttention(row) {
    const before = previous.get(row.case.id);
    return affectedIds.has(row.case.id) || row.target.status === 'ERROR' ||
      row.evaluations.some(e => ['FAIL', 'ERROR', 'UNKNOWN'].includes(e.status)) ||
      (before && (before.target.status === 'ERROR' || before.evaluations.some(e => ['ERROR', 'UNKNOWN'].includes(e.status))));
  }
  const affectedCount = candidate.cases.filter(needsAttention).length;
  const affectedTopics = [...new Set(candidate.cases.filter(needsAttention).map(row => row.case.category))];
  const warningCount = comparison.gates.filter(gate => gate.rule.severity === 'warn' && gate.status === 'FAIL').length;
  const unmetCount = comparison.gates.filter(gate => gate.rule.severity === 'block' && gate.status !== 'PASS').length;
  const outcome = node('section', undefined, `outcome ${comparison.status}`);
  const outcomeTitle = comparison.status === 'ERROR' ? 'Evaluation incomplete' : comparison.status === 'FAIL' ? 'Change blocked' : warningCount ? 'Passed with warnings' : 'Passed required checks';
  const outcomeText = comparison.status === 'ERROR' ? 'An execution or evidence problem prevented a reliable decision. Resolve the reported errors, then test again.' : comparison.status === 'FAIL' ? `${unmetCount} required ${unmetCount === 1 ? 'check was' : 'checks were'} not met. Review the differences below before accepting this change.` : warningCount ? `${warningCount} warning ${warningCount === 1 ? 'check needs' : 'checks need'} review. Required checks passed; inspect the warnings before accepting the change.` : 'The candidate met all configured required checks. This does not guarantee correctness beyond this test set.';
  outcome.append(node('h2', outcomeTitle), node('p', outcomeText));
  if (affectedTopics.length) outcome.append(node('p', `Topics needing attention: ${affectedTopics.join(', ')}.`, 'affected-topics'));
  const actions = node('div', undefined, 'outcome-actions');
  const review = node('button', affectedCount ? `Review ${affectedCount} affected ${affectedCount === 1 ? 'question' : 'questions'}` : 'Review all questions');
  const rerun = node('button', 'How to test again', 'secondary');
  rerun.addEventListener('click', () => toggleHelp(true));
  actions.append(review, rerun); outcome.append(actions);
  overview.append(outcome);

  overview.append(node('p', 'Scores compare the reference version (baseline) with your changed version (candidate).', 'score-guide'));
  const gates = node('div', undefined, 'gates');
  for (const gate of comparison.gates) {
    const card = node('div', undefined, 'gate');
    const heading = node('div', undefined, 'gate-title');
    heading.append(node('strong', `${metricLabel(gate.rule.metric)}${gate.rule.category ? ` · ${gate.rule.category}` : ''}`), badge(gate.status));
    const spec = candidate.evaluators.find(e => e.metric === gate.rule.metric);
    card.append(node('p', checkDescription(spec, gate.rule.metric), 'metric-help'));
    const values = node('div', undefined, 'gate-values');
    const before = node('span', metricValue(gate.baseline, gate.rule.metric), 'before');
    before.setAttribute('aria-label', `Baseline: ${metricValue(gate.baseline, gate.rule.metric)}`);
    const after = node('strong', metricValue(gate.candidate, gate.rule.metric));
    after.setAttribute('aria-label', `Candidate: ${metricValue(gate.candidate, gate.rule.metric)}`);
    values.append(before, node('span', '→', 'arrow'), after);
    const explanation = node('details');
    explanation.append(node('summary', 'Decision details'), node('p', `${gate.rule.severity === 'warn' ? 'Warning check' : 'Required check'} · ${gate.explanation}`));
    const deltaText = gate.delta == null ? 'No reliable comparison available' : ['latency_ms', 'p95_latency_ms', 'cost'].includes(gate.rule.metric) ? `${metricValue(gate.delta, gate.rule.metric, true)} change from baseline` : `${Math.abs(gate.delta * 100).toFixed(1)} percentage points ${gate.delta < 0 ? 'lower' : gate.delta > 0 ? 'higher' : 'change'}`;
    card.prepend(heading);
    card.append(values, node('p', deltaText, 'delta'), explanation);
    gates.append(card);
  }
  overview.append(gates);
  overview.append(node('p', sourceDescription(candidate), 'provenance'));
  detail.append(overview);
  const filters = node('div', undefined, 'filters');
  const filter = node('select'); filter.setAttribute('aria-label', 'Filter questions');
  for (const [value, label] of [['failed', 'Questions needing attention'], ['all', 'All questions']]) {
    const option = node('option', label); option.value = value; filter.append(option);
  }
  filters.append(node('h2', 'Question details'), filter); detail.append(filters);
  const cases = node('div'); detail.append(cases);
  review.addEventListener('click', () => {
    filter.value = affectedCount ? 'failed' : 'all';
    renderCases();
    filters.scrollIntoView({behavior:'smooth', block:'start'});
    filter.focus({preventScroll:true});
  });
  function renderCases() {
    cases.replaceChildren();
    for (const row of candidate.cases) {
      const before = previous.get(row.case.id);
      if (filter.value === 'failed' && !needsAttention(row)) continue;
      const card = node('article', undefined, 'card');
      const head = node('div', undefined, 'case-head');
      const meta = node('div', undefined, 'case-meta');
      meta.append(node('span', row.case.category), node('span', '·'), node('span', row.case.id));
      if (row.case.critical) meta.append(node('span', 'Must-pass question', 'critical'));
      head.append(meta, node('p', typeof row.case.input === 'string' ? row.case.input : JSON.stringify(row.case.input), 'case-question'));
      if (row.case.reference_answer != null) {
        const reference = node('details', undefined, 'reference');
        reference.append(node('summary', 'Expected answer'), node('p', `${row.case.reference_answer} (evaluation only)`));
        head.append(reference);
      }
      card.append(head);
      const panels = node('div', undefined, 'answers');
      if (before) panels.append(answerPanel('ORIGINAL VERSION · BASELINE', before, baseline));
      panels.append(answerPanel('CHANGED VERSION · CANDIDATE', row, candidate)); card.append(panels); cases.append(card);
    }
    if (!cases.childElementCount) cases.append(node('p', 'No individual questions need attention in this view. Check the score decisions above, or choose All questions to inspect every answer.'));
  }
  filter.addEventListener('change', renderCases); renderCases();
}
async function selectExperiment(id) {
  selected = id;
  const sequence = ++requestSequence;
  for (const button of history.querySelectorAll('button')) {
    const active = button.dataset.id === id;
    button.classList.toggle('selected', active);
    button.setAttribute('aria-pressed', String(active));
  }
  try {
    const experiment = await get(`/api/experiments/${encodeURIComponent(id)}`);
    if (sequence !== requestSequence) return;
    showExperiment(experiment);
  } catch (error) { if (sequence === requestSequence) notice.textContent = error.message; }
}
async function refresh() {
  try {
    const response = await get('/api/experiments');
    notice.textContent = response.invalid_artifacts ? `${response.invalid_artifacts} incomplete or invalid artifact folders were skipped.` : '';
    history.replaceChildren();
    for (const run of response.experiments) {
      const button = node('button', undefined, 'run'); button.dataset.id = run.directory;
      const top = node('div', undefined, 'run-top');
      top.append(node('strong', run.dataset), badge(run.status));
      button.append(top, node('span', `${run.baseline} → ${run.candidate}`, 'muted'), node('span', new Date(run.created_at).toLocaleString(), 'muted'));
      button.addEventListener('click', () => selectExperiment(run.directory)); history.append(button);
    }
    if (response.experiments.length) {
      const id = response.experiments.some(run => run.directory === selected) ? selected : response.experiments[0].directory;
      await selectExperiment(id);
    } else { selected = null; requestSequence++; detail.replaceChildren(emptyTemplate.cloneNode(true)); history.append(node('p', 'No saved tests yet. Start with the demonstration on the right.', 'muted')); }
  } catch (error) { notice.textContent = error.message; }
}
document.querySelector('#help').addEventListener('click', () => toggleHelp(document.querySelector('#getting-started').hidden));
document.querySelector('#refresh').addEventListener('click', refresh);
refresh();
